### ISSUE TITLE
Add sample configuration when using monolog with Symfony

### ISSUE THREAD

**Issue by nicodemuz** [brefphp/logger#4]

**Comment by mnapoli** [comment]
I'm not sure what this issue is about.

**Comment by nicodemuz** [comment]
I ended up using the following configuration:

```
monolog:
    handlers:
        main:
            type: fingers_crossed
            path: "php://stderr"
            action_level: WARNING
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "php://stderr"
            level: debug
```

It would be great to include sample configuration that uses classes from brefphp/logger.
